### ISSUE TITLE
missing frame, fps, q, size field in progress callback

### ISSUE THREAD

**Issue by hados99** [legraphista/ffmpeg-progress-wrapper#4]
Hi, thanks for this lightweight and convenient library.

From version 0.4.0, data from progress event does not contains frame, fps, q, size fields.

IMO, changed regex causes wrong result - 69b10c33faf424a3de598e538e75e53a422d2f6e

I compared the result 0.4.0 and 0.3.2 (successful) as below

* version 0.3.2

```
-----------------raw-----------------
frame=  207 fps=0.0 q=-0.0 size=N/A time=00:00:06.97 bitrate=N/A speed=13.9x
-----------------progress-----------------
{ frame: 207,
  fps: '0.0',
  q: '-0.0',
  size: 'N/A',
  time: 6970,
  bitrate: 'N/A',
  speed: 13.9,
  progress: 0.014223909228194767,
  eta: 34751 }
```

* version 0.4.0

```
-----------------raw-----------------
frame=  214 fps=0.0 q=-0.0 size=N/A time=00:00:07.20 bitrate=N/A speed=14.4x
-----------------progress-----------------
{ time: 7200,
  bitrate: 'N/A',
  speed: 14.4,
  progress: 0.014693277825394882,
  eta: 33529 }
```

**Comment by legraphista** [comment]
Hi! Thanks for the feedback!
Yes, I seem to have overlooked the fact that the input text is from the right of the regex match, not the whole line. 
Fix has been applied in https://github.com/legraphista/ffmpeg-progress-wrapper/commit/54dfd915d8103add5887dabca9d943a7b217bb04 and pushed as `v0.4.1` on npm
